var acrobatSkills = [{skill:"<span class='bold'>Acrobat Skill Chance of Success:</span>", success:"• Level: 1, CS: 87, FA: 25, HS: 10, MS: 20, TW: 60"},
{skill:"<span class='bold'>Climb sheer surfaces (CS):</span>", description:"• A roll is rewuired for each 100' to be climbed. If the roll fails, the acrobat falls at the half way point, suffering falling damage."},
{skill:"<span class='bold'>Falling (FA):</span>", description:"• When able to tumble, acrobats suffer no damage from the first 10' of any fall. Damage due to falling from a greater height is reduced by the listed percentage (round down)."},
{skill:"<span class='bold'>Hide in shadows (HS):</span>", description:"• The acrobat must be motionless - attacking or moving while hiding is not possible."},
{skill:"<span class='bold'>Move silently (MS):</span>", description:"• An acrobat may attempt to sneak past enemies unnoticed."},
{skill:"<span class='bold'>Tightrope walking (TW):</span>", description:"• Acrobats can walk along tightropes, narrow beams, and ledges at up to half their normal movement rate. A roll is required every 60'. Failure indicates that the acrobat falls and suffers falling damage. Windy conditions may reduce the chance of success by up to 20%. Holding a balance pole increases the chance of success by 10%."},
{skill:"<span class='bold'>Evasion:</span>", description:"• When retreating from melee, an acrobat's ability to tumble negates the opponent's usual +2 bonus to hit."},
{skill:"<span class='bold'>Jumping:</span>", description:"• With a 20' run-up, an acrobat can jump accross a 10' wide pit or chasm (or 20' wide when aided by the use of a pole). Also when using a pole, an acrobat can jump over a 10' high wall or onto a 10' high ledge. Suitable poles for jumping include: 10' poles, polearms, spears, staves."},
{skill:"<span class='bold'>Tumbling Attack:</span>", description:"• Usinf the falling or jumping abilities, an acrobat can make a tumbling melee attack. The attack inflicts double damage if successful. Against an unaware opponent, the acrobat also gains a +4 bonus to hit."}];

var assassinSkills = [{skill:"<span class='bold'>Assassin Skill Chance of Success:</span>", success:"• Level: 1, AS: 0, CS: 87, HN: 1-2, HS: 10, MS: 20"},
{skill:"<span class='bold'>Assassination (AS):</span>", description:"• When attacking an unaware humanoid from behind, an assassin gains a +4 bonus to hit. If the attack succeeds, the victim must save versus death with a penalty dependent on the assassin's level (noted in the table opposite). If the save fails, the victim is instantly killed, otherwise the assassin's attack inflicts normal damage."},
{skill:"<span class='bold'>Climb sheer surfaces (CS):</span>", description:"• A roll is required for each 100' to be climbed. If the roll fails, the assassin falls at the half way point, suffering falling damage."},
{skill:"<span class='bold'>Hear noise (HN):</span>", description:"• In a quiet environment (e.g. not in combat), an assassin may attempt to listen at a door or to hear the sounds of something (e.g. a wandering monster) approaching."},
{skill:"<span class='bold'>Hide in shadows (HS):</span>", description:"• Requires the assassin to be motionless - attacking or moving while hiding is not possible."},
{skill:"<span class='bold'>Move silently (MS):</span>", description:"• An assassin may attempt to sneak past enemies unnoticed."},
{skill:"<span class='bold'>Disguise:</span>", description:"• Characters of any class may don disguises, but assassins are masters of the art - able to create disguises that pass even close scrutiny.", detection:"• Chance of detection: Everyone the assassin meets has a 2% chance of spotting the disguise. This roll is repeated once every subsequent day of meeting.", posing:"• Posing as another class, race, or sex: Increases the chance of being detected by 2% per change.", height:"• Height and weight: A disguise may alter height (up to 3 inches shorter or 5 inches taller) or weight (slightly thinner, much bulkier)."},
{skill:"<span class='bold'>Poison:</span>", description:"• Victims of a poisoning by an assassin suffer a -2 penalty to the saving throw."}];

var barbarianSkills = [{skill:"<span class='bold'>Barbarian Skill Chance of Success:</span>", success:"• level: 1, CS: 87, HD: 10, MS: 20"},
{skill:"<span class='bold'>Climb sheer surfaces (CS):</span>", description:"• Only applies to natural surfaces (e.g. tree trunks, cliff faces). A skill roll is required for each 100' height to be climbed. Failure indicates that the barbarian falls at the halfway point, suffering falling damage."},
{skill:"<span class='bold'>Hide in undergrowth (HD):</span>", description:"• requires the barbarian must be motionless - attacking or moving while hiding is not possible."},
{skill:"<span class='bold'>Move silently (MS):</span>", description:"• A barbarian may attempt to sneak past enemies."},
{skill:"<span class='bold'>Cure Poison:</span>", description:"• In the wilderness, a barbarian can gather herbs to concoct an antidote to natural poisons. This takes one turn per character to be cured. Each subject may make a second save versus poison to end the effects."},
{skill:"<span class='bold'>Fear of Magic:</span>", description:"• Barbarians are mistrustful of magic and will refuse to knowingly use or come under the influence of spells or magic items. Barbarians will accept divine magic associated with their tribal religion."},
{skill:"<span class='bold'>Foraging and hunting:</span>", description:"• A party with a barbarian can more easily find food when foraging (2-in-6) or prey when hunting (5-in-6)."}];

var bardSkills = [{skill:"<span class='bold'>Anti-Charm:</span>", description:"• While the bard plays music and sings, allies within 30' are immune to song-based magical effects and the beguiling powers of sylvan creatures or fairies. Allies already under the effect of such magic may make another saving throw with a +4 bonus."},
{skill:"<span class='bold'>Enchantment:</span>", description:"• By playing music and singing, the bard can fascinate subjects in a 30' radius. This ability does not function in combat.", numberOfSubjects:"• Number of subjects: Up to 2HD of creatures per level of the bard are affected. The bard may choose to target a specific individual or a group (in which case, the affected individuals are determined randomly).", typeOfSubjects:"• Type of subjects: At 1st level, the bard can fascinate persons.", effect:"• Effect: Each subject must save versus spells or be fascinated, as follows:", rapt:"• Rapt: Fascinated subjects' attention is fully bent on the bard's performance, as long as it continues.", follow:"• Follow: The bard may walk while playing. Fascinated subjects will follow.", interruptions:"• Interruptions: If the performance is interrupted (e.g. by loud noise or violence), the fascination ends immediately."},
{skill:"<span class='bold'>Charming Fascinated Subjects:</span>", description:"• If the bard performs for at least one turn and the performance ends without interruption, fascinated subjects may be placed under a deeper charm. Each subject must make another save versus spells (with a +2 bonus) or be charmed for one turn per level of the bard:", friendship:"• Friendship: Charmed subjects regard the bard as a trusted friend and ally and will come to the bard's defence.", commands:"• Commands: If they share a language, charmed subjects will obey the bard's commands.", alignment:"• Alingment: Commands that contradict the charmed creature's nature or alignment may be ignored.", suicidal: "• Suicidal commands: Charmed subjects never obey suicidal or obviously harmful orders."}];

var druidSkills = [{skill:"<span class='bold'>Spells:</span>", spells:"• level 1 spells per day: 1"},
{skill:"<span class='bold'>Divine Magic:</span>", holySymbol:"• Holy symbol: A druid must carry a holy symbol: a sprig of mistletoe which the character must harvest.", disfavor:"• Deity disfavor: Druids must be faithful to the tenets of their alignment and religion. Druids who fall from favour with their deity may incur penalties.", research:"• Magical research: A druid of any level may spend time and money on magical research. This allows them to create new spells or other magical effects associated with their deity.", casting:"• Spell casting: A druid may pray to receive spells from nature. The power and number of spells available to a druid are determined by the character's perience level.", magicItems:"• Using magic items: As spell casters, druids can use magic scrolls of spells on their spell list. They can also use items that may only be used by divine spell casters (e.g. some staves). Druids may not use magical books or tomes."},
{skill:"<span class='bold'>Energy Resistance:</span>", description:"• Druids gain +2 bonus to saving throws against electricity (lightning) and fire."},
{skill:"<span class='bold'>Identification:</span>", description:"• Druids can identify all plants and animals and can disern pure water."},
{skill:"<span class='bold'>Languages:</span>", description:"• Druids speak a secret tongue known only to their sect. At each level above 2nd, a druid also learns to speak a language used by creatures of Sylvan forests (e.g. dryads, green dragons, pixies, treants)."},
{skill:"<span class='bold'>Path-Finding:</span>", description:"• A party with a druid has only a 1-in-6 chance of getting lost in woodlans."}];

var illusionistSkills = [{skill:"<span class='bold'>Spells:</span>", spells:"• level 1 spells per day: 1"},
{skill:"<span class='bold'>Arcane Magic:</span>", research:"• Magical research: An illusionist of any level may spend time and money on magical research. This allows them to add new spells to their spell book and to research other magical effects.", casting:"• Spell casting: Illusionists carry spell books containing the formulae for arcane spells. The level progression table shows both the number of spells in the illusionist's spell book and the number they may memorize, determined by the character's experience level. Thus, a 1st level illusionist has one spell in their spell book", magicItems:"• Using magic items: As spell casters, illusionists are able to use magic scrolls of spells on their spell list. They can also use items that may only be used by arcane spell casters (e.g. magic wands). They are, however, not able to use magic items with effects that cause direct damage (e.g. a wand that shoots fireballs)."}];

var knightSkills = [{skill:"<span class='bold'>Horsemanship:</span>", description:"• Assessing steeds: Knights are expert riders and can assess the worth of any steed. This allows a knight to determine whether an animal has low, average, or high hit points for its type."},
{skill:"<span class='bold'>Mounted Combat:</span>", description:"• Knights gain a +1 bonus to attack rolls when mounted."},
{skill:"<span class='bold'>Strength of Will:</span>", fear:"• Fear: Knights are immune to all supernatural fear effects.", beguilement:"• Knights gain a +4 bonus to saving throws against hold spells, charms, mind control, hypnotism, suggestion, etc. They gain a +2 bonus to saving throws against illusion, and gain a saving throw (one is not normally allowed) against sleep spells."}];

var paladinSkills = [{skill:"<span class='bold'>Divine Magic:</span>", holySymbol:"• Holy symbol: A paladin must cary a holy symbol.", dieityDisfavor:"• Paladins must be faithful to the tenets of their alignment and religion. Paladins who fall from favour with their deity may incur penalties."},
{skill:"<span class='bold'>Holy Resistance:</span>", description:"• Paladins are immune to all diseases."},
{skill:"<span class='bold'>Laying on Hands:</span>", description:"• Once per day, a paladin can heal 2 hit points per level by laying their hands on wounded characters. Additionally, a paladin of 5th level or higher may cure disease once per week by laying on hands."},
{skill:"<span class='bold'>Vow of Humility:</span>", description:"• A paladin may keep only a total of one suit of magical armour, one magical shield, and one magical melee weapon. They must also donate 10% of all income to a Lawful religious institution."}];

var rangerSkills = [{skill:"<span class='bold'>Awareness:</span>", description:"• Rangers are only surprised on a roll of 1. This may mean that a ranger is able to act in the surprise round while their companions are surprised."},
{skill:"<span class='bold'>Foraging and Hunting:</span>", description:"• A party with a ranger can more easily find food when foraging (2-in-6) or prey when hunting (5-in-6)."},
{skill:"<span class='bold'>Limited Possessions:</span>", description:"• A ranger may only keep wealth and possessions that can be kept on their person or mount. Excess must be donated to worthy causes (not other PCs!)."},
{skill:"<span class='bold'>Pursuit:</span>", description:"• When the ranger's party pursues an opposing group in the wilderness, the chance of evasion is reduced by 10%."},
{skill:"<span class='bold'>Steath:</span>", description:"• In the wilderness, a ranger has a 3-in-6 chance of hiding and a 3-in-6 chance of moving silently."},
{skill:"<span class='bold'>Tracking:</span>", description:"• Rangers can identify and follow tracks. This skill improves as the character gains levels (see the table to the right). Success may be modified by the following factors:", softGround:"• Soft/ hard ground: +20% to -50%.", sizeOfGroup:"• Size of group being tracked: +2% per creature beyond the first.", passing:"• Passing through an area where other tracks mingle: -50%.", ageOfTracks:"• Age of tracks: -5% per 12 hours.", rainfall:"• Rainfall: -25% per hour.", hidenTracks:"• Efforts made to hide tracks: -25%."}];

var clericSkills = [{skill:"<span class='bold'>Turning the Undead Chart:</span>", description:"• level 1, Monster hit dice/ turn chance: 1HD/ 7, 2HD/ 9, 2*HD/ 11", caviat:"• * 2HD monsters with a special ability (i.e. with an astrisk next to their HD rating, in the monster description."},
{skill:"<span class='bold'>Turning the Undead:</span>", description:"• Clerics can invoke the power of their deity to repel undead monsters encountered. To turn the undead, the player rolls 2d6. The referee then consults the table opposite, comparing the roll against the HD of the type of undead monsters targeted.", turning:"• Turned undead: Will leave the area, if possible, and will not harm or make contact with the cleric.", excess:"• Excess: Rolled Hit Dice that are not sufficient to affect a monster are wasted.", minimumEffect:"• Minimum effect: At least one undead monster will always be affected on a successful turning.", mixed:"• Mixed groups: If turn undead is used against a mixed group of undead monsters of different types, those with the lowest HD are effected first."}];

var fighterSkills = [{skill:"<span class='bold'>Stronghold:</span>", description:"• Any time a fighter wishes (and has sufficient money), they can build a castle or stronghold and control the surrounding lands."}];

var magicUserSkills = [{skill:"<span class='bold'>Spells:</span>", spells:"• level 1 spells per day: 1"},
{skill:"<span class='bold'>Arcane Magic:</span>", research:"• Magical research: A magic-user of any level may spend time and money on magical research. This allows them to add new spells to their spell book and to research other magical effects.", casting:"• Magic-users carry spell books containing the formulae for arcane spells. The spell casting chart shows both the number of spells in the magic-user's spell book and the number they may memorize, determined by the character's experience level.", magicItems:"• Using magic items: As spell casters, magic-users are able to use magic scrolls of spells on their spell list. They can also use items that may only be used by arcane spell casters (e.g. magic wands)."}];

var thiefSkills = [{skill:"<span class='bold'>Thief Skill Chance of Success:</span>", success:"• Level 1, CS: 87, TR: 10, HN: 1-2, HS: 10, MS: 20, OL: 15, PP: 20"},
{skill:"<span class='bold'>Thief Skills:</span>", description:"• Thieves can use the following skills, with the chance of success shown opposite:", climb:"• Climb sheer surfaces (CS): A roll is required for each 100' to be climbed. If the roll fails, the thief falls at the halfway point, suffering falling damage.", removeTraps:"• Find or remove treasue traps (TR): A roll is required to find a treasure trap and then another to remove it. This may be attempted only once per trap", hearNoise:"• Hear noise (HN): In a quiet environment (e.g. not in combat), a thief may attempt to listen at a door or to hear the sounds of something (e.g. a wandering monster) approaching.", hide:"• Hide in shadows (HS): Requires the thief to be motionless - attacking or moving while hiding is not possible.", moveSilently:"• Move silently (MS): A thief may attempt to sneak past enemies unnoticed.", openLocks:"• Open locks: Requires thieves' tools. A thief can only try this skill once per lock. If the roll fails, the thief may not try the same lock again before gaining an experience level.", pickPockets:"• Pick pockets (PP): For victims above 5th level, the thief's roll is penalised by 5% for every level above 5th. There is always at least a 1% chance of failure. A roll of more than twice the percentage required for success means that the attempted theft is noticed."},
{skill:"<span class='bold'>Back-Stab:</span>", description:"• When attacking an unaware opponent from behind, a thief receives a +4 bonus to hit and doubles any damage dealt."}];

var necromancerSkills = [{skill:"<span class='bold'>Spells:</span>", spells:"• level 1 spells per day: 1"},
{skill:"<span class='bold'>Arcane Magic:</span>", research:"• Magical research: A necromancer of any level may spend time and money on magical research. This allows them to add new spells to their spell book and to research other magical effects.", casting:"• Spell casting: Necromancers carry spell books containing the formulae for arcane spells. The level progression table shows both the number of spells in the necromancer's spell book and the number they may memorize, determined by the character's experience level.", magicItems:"• Using magic items: As spell casters, necromancers are able to use magic scrolls of spells on their spell list. They can also use items that may only be used by arcane spell casters (e.g. magic wands). They are, however, not able to use magic items with effects that charm or control living creatures, including humans (e.g. a ring that controls animals)."}];

function classSkillsDisplayer(classSkillsArray){    
    
    for(let obj of classSkillsArray){
        for(let key in obj){
            oseCharacterAbilitySkillsWeapons.innerHTML += obj[key] + "<br>";
        }
    }
};