var clericLevelOneSpells = [{spell:"<span class='bold'>Cure Light Wounds:</span>", duration:"Duration: Instant", range:"Range: The caster or a creature touched", decription:"This spell has two uses", useOne:"1. Healing a living subject: Restores 1d6+1 hit points of damage. This cannot grant more hit points than the subject's normal maximum.", useTwo:"2. Curing Paralysis: Paralysing effects are negated.", reversed:"Reversed: Cause Light Wounds", decriptionTwo:"Inflicts 1d6+1 hit points of damage to a touched creature. In combat, a melee attack roll is required."},
{spell:"<span class='bold'>Detect Evil:</span>", duration:"Duration: 6 turns", range:"Range: 120'", decription:"Objects enchanted for evil purposes or living beings with evil ntentions are caused to magically glow.", asideOne:"• Intent Only: This spell does not grant the ability to read minds, but only grants a general sense of evil intent.", asideTwo:"• Definition of evil: The referee must decide what is “evil”. Some things that are potentially harmful, like traps, are not “evil.”"},
{spell:"<span class='bold'>Detect Magic:</span>", duration:"Duration: 2 turns", range:"Range:60'", decription:"Enchanted objects, areas, or creatures are caused to glow. Both permanent and temporary enchantments are revealed."},
{spell:"<span class='bold'>Light:</span>", duration:"Duration: 12 turns", range:"Range:120'", decription:"This spell has three usages:", useOne:"1. Conjuring light: In a 15' radius. The magical light is sufficient for reading, but is not as bright as daylight. The spell may be cast upon an object, in which case the light moves with the object.", useTwo:"2. Blinding a creature: By casting the spell upon its eyes. If the target fails a saving throw versus spells, it is blinded for the duration. A blind creature cannot attack.", seThree:"3. Cancelling darkness: Light may cancel a darkness spell.", reversed:"Reversed: Darkness", descriptionTwo:"Creates a 15' radius area of magical blackness, preventing normal sight (but not infravision). Like light, it may alternatively be used to blind creatures or to dispel a light spell."},
{spell:"<span class='bold'>Protection from Evil:</span>", duration:"Duration: 12 turns", range:"Range: The caster", decription:"This spell wards the caster from attacks by creatures of another alignment, as follows:", useOne:"• Bonuses: The caster gains a +1 bonus to saving throws against attacks or special abilities of affected creatures.", useTwo:"• Affected creatures' attacks: Against the caster are penalised by –1.", useThree:"• Enchanted, constructed, or summoned creatures: The spell additionally prevents such creatures from attacking the caster in melee, though they may still make ranged attacks. If the caster engages such a creature in melee, this protection is broken (the caster still gains the save and attack bonuses mentioned above)."},
{spell:"<span class='bold'>Purify Food and Water</span>", duration:"Duration: Permanent", range:"Range: 10'", decription:"This spell makes spoiled, rotten, poisonous, or otherwise contaminated food and water pure and suitable for eating and drinking. One of the following may be affected:", useOne:"• Drink: 6 quarts", useTwo:"• Rations: One trail ration (iron or standard).", useThree:"• Unpreserved food: A quantity sufficient for 12 human-sized beings."},
{spell:"<span class='bold'>Remove Fear:</span>", duration:"Duration: 2 turns", range:"Range: The caster or a creature touched", decription:"The creature touched is calmed and purged of fear. Magically induced fear may be dispelled, but this requires the subject to make a saving throw versus spells. The save is modified by +1 per level of the caster.", reversed:"Reversed: Cause Fear", decriptionTwo:"Will cause a target within 120' to flee for the duration unless it saves versus spells."},
{spell:"<span class='bold'>Resist Cold:</span>", duration:"Duration: 6 turns", range:"Range: 30'", decription:"All creatures within range are protected from cold, as follows:", useOne:"• Normal cold: Unharmed by non-magical freezing temperatures.", useTwo:"• Save bonus: Gain a +2 bonus to all saving throws versus cold-based magical or breath attacks.", useThree:"• Cold-based damage: Is reduced by 1 point per damage die rolled. (Each die inflicts a minimum of 1 hit point damage.)"}];

var magicUserLevelOneSpells = [{spell:"<span class='bold'>Charm Person:</span>", duration:"Duration: One or more days (see below)", range:"Range: 120'", decription:"A single human, demihuman, or human-like monster must save versus spells or be charmed, as follows:", useOne:"• Friendship: The subject regards the caster as its trusted friend and ally and will come to the caster's defence.", useTwo:"• Commands: If they share a language, the caster may give the charmed creature commands, which it will obey.", useThree:"• Subject's nature: Commands that contradict the charmed creature's habits or alignment may be ignored.", useFour:"• Suicidal commands: An affected creature never obeys suicidal or obviously harmful orders.", restrictions:"Restrictions: Undead and human-like monsters of greater than 4+1 HD are not affected.", durationDecription:"Duration: The charm lasts indefinitely, but the subject is allowed to make further saves versus spells at intervals, depending on its INT score. If one of these saves succeeds, the spell ends.", intCheckOne:"• INT 3–8: New save once every month.", intCheckTwo:"• INT 9–12: New save each week.", intCheckThree:"• INT 13–18: New save once every day."},
{spell:"<span class='bold'>Detect Magic:</span>", duration:"Duration: 2 turns", range:"Range: 60'", decription:"Enchanted objects, areas, or creatures are caused to glow. Both permanent and temporary enchantments are revealed."},
{spell:"<span class='bold'>Floating Disc:</span>", duration:"Duration: 6 turns", range:"Range: 6'", decription:"The caster conjures a slightly concave, circular disc of magical force that follows them about and carries loads.", useOne:"• Dimensions: The disc is 3 feet in diameter and 1 inch deep at its centre.", useTwo:"• Load: It can hold a maximum load of 5,000 coins (500 pounds).", useThree:"• Motion: The disc floats at waist height and remains level, floating along horizontally within spell range.", useFour:"• End: When the disc winks out at the end of the spell's duration, anything it was supporting is dropped."},
{spell:"<span class='bold'>Hold Portal:</span>", duration:"Duration: 2d6 turns", range:"Range: 10'", decription:"This spell magically holds shut a door, gate, window, or other kind of portal.", useOne:"• Opening by magic: A knock spell opens the held portal instantly.", useTwo:"• Opening by force: Creatures with at least 3 Hit Dice more than the caster can open the held portal with one round of effort."},
{spell:"<span class='bold'>Light:</span>", duration:"Duration: 6 turns +1 per level", range:"Range: 120'", decription:"This spell has three usages:", useOne:"1. Conjuring light: In a 15' radius. The magical light is sufficient for reading, but is not as bright as daylight. The spell may be cast upon an object, in which case the light moves with the object.", useTwo:"2. Blinding a creature: By casting the spell upon its eyes. If the target fails a saving throw versus spells, it is blinded for the duration. A blind creature cannot attack.", useThree:"3. Cancelling darkness: Light may cancel a darkness spell (see below).", reverse:"Reversed: Darkness", descriptionTwo:"Creates a 15' radius area of magical blackness, preventing normal sight (but not infravision). Like light, it may alternatively be used to blind creatures or to dispel a light spell."},
{spell:"<span class='bold'>Magic Missile:</span>", duration:"Duration: 1 turn", range:"Range: 150'", decription:"This spell conjures a glowing dart of energy that the caster may choose to shoot at a visible target within range.", useOne:"• Hit: The missile hits unerringly (no attack roll or saving throw is required).", useTwo:"• Damage: The missile inflicts 1d6+1 damage.", useThree:"•Higher level casters: May conjure more missiles: two additional missiles are conjured per five experience levels the caster has gained (i.e. three missiles at 6th–10th level, five missiles at 11th–15th level, etc.). Multiple missiles may be directed at a single target."},
{spell:"<span class='bold'>Protection from Evil:</span>", duration:"Duration: 6 turns", range:"Range: The caster", decription:"This spell wards the caster from attacks by creatures of another alignment, as follows:", useOne:"• Bonuses: The caster gains a +1 bonus to saving throws against attacks or special abilities of affected creatures.", useTwo:"• Affected creatures’ attacks: Against the caster are penalised by –1.", useThree:"•Enchanted, constructed, or summoned creatures: The spell additionally prevents such creatures from attacking the caster in melee, though they may still make ranged attacks. If the caster engages such a creature in melee, this protection is broken (the caster still gains the save and attack bonuses mentioned above)."},
{spell:"<span class='bold'>Read Languages:</span>", duration:"Duration: 2 turns", range:"Range: The Caster", decription:"For the duration of this spell, the caster may read any language, coded message, map, or other set of written instructions. This spell does not grant any ability to speak unknown languages."},
{spell:"<span class='bold'>Read Magic:</span>", duration:"Duration: 1 turn", range:"Range: The caster", decription:"By means of read magic, the caster can decipher magical inscriptions or runes, as follows:", useOne:"• Scrolls: The magical script of a scroll of arcane spells can be understood. The caster is then able to activate the scroll at any time in the future.", useTwo:"• Spell books: A spell book written by another arcane spell caster can be deciphered.", useThree:"• Inscriptions: Runes or magical words inscribed on an object or surface can be understood.", useFour:"• Reading again: Once the caster has read a magical inscription using read magic, they are thereafter able to read that particular writing without recourse to the use of this spell."},
{spell:"<span class='bold'>Shield:</span>", duration:"Duration: 2 turns", range:"Range: The caster", decription:"Creates an invisible field of force that gives the caster an improved AC:", useOne:"• Against missile attacks: AC 2 [17].", useTwo:"• Against other attacks: AC 4 [15]."},
{spell:"<span class='bold'>Sleep:</span>", duration:"Duration: 4d4 turns", range:"Range: 240'", decription:"A sleep spell causes a magical slumber to come upon creatures, excluding the undead. The spell may target either:", useOne:"1. A single creature with 4+1 HD.", useTwo:"2. A total of 2d8 Hit Dice of creatures of 4 HD or lower each.", descriptionTwo:"When targeting creatures of 4 HD or less, the following rules apply:", useThree:"• Weakest first: Targets with the least HD are affected first.", useFour:"• HD: Treat monsters with less than 1 HD as having 1 HD and monsters with a fixed hit point bonus as having the flat HD. (For example, a 3+2 HD monster would be treated as having 3 HD.)", useFive:"• Excess: Rolled Hit Dice that are not sufficient to affect a creature are wasted.", useSix:"Killing: Creatures enchanted by this spell are helpless and can be killed instantly with a bladed weapon.", useSeven:"Awakening: Slapping or wounding awakens an affected creature."},
{spell:"<span class='bold'>Ventriloquism:</span>", duration:"Duration: 2 turns", range:"Range: 60'", decription:"The caster may make their voice appear to come from any location or source (e.g. a statue or animal) within range."}];

var druidLevelOneSpells = [{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""}];

var illusionistLevelOneSpells = [{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""}];

var necromancerLevelOneSpells = [{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""},
{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""}];




//{spell:"<span class='bold'> </span>", duration:"Duration:", range:"Range:", decription:""}