var acrobatSkills = [{skill:"Acrobat Skill Chance of Success:", level:1, cs:87, fa:25, hs:10, ms:20, tw:60},
{skill:"Climb sheer surfaces (CS):", description:"• A roll is rewuired for each 100' to be climbed. If the roll fails, the acrobat falls at the half way point, suffering falling damage."},
{skill:"Falling (FA):", description:"• When able to tumble, acrobats suffer no damage from the first 10' of any fall. Damage due to falling from a greater height is reduced by the listed percentage (round down)."},
{skill:"Hide in shadows (HS):", description:"• The acrobat must be motionless - attacking or moving while hiding is not possible."},
{skill:"Move silently (MS):", description:"• An acrobat may attempt to sneak past enemies unnoticed."},
{skill:"Tightrope walking (TW):", description:"• Acrobats can walk along tightropes, narrow beams, and ledges at up to half their normal movement rate. A roll is required every 60'. Failure indicates that the acrobat falls and suffers falling damage. Windy conditions may reduce the chance of success by up to 20%. Holding a balance pole increases the chance of success by 10%."},
{skill:"Evasion:", description:"• When retreating from melee, an acrobat's ability to tumble negates the opponent's usual +2 bonus to hit."},
{skill:"Jumping:", description:"• With a 20' run-up, an acrobat can jump accross a 10' wide pit or chasm (or 20' wide when aided by the use of a pole). Also when using a pole, an acrobat can jump over a 10' high wall or onto a 10' high ledge. Suitable poles for jumping include: 10' poles, polearms, spears, staves."},
{skill:"Tumbling Attack:", description:"• Usinf the falling or jumping abilities, an acrobat can make a tumbling melee attack. The attack inflicts double damage if successful. Against an unaware opponent, the acrobat also gains a +4 bonus to hit."}];

var assassinSkills = [{skill:"Assassin Skill Chance of Success:", level:1, as:0, cs:87, hn:"1-2", hs:10, ms:20},
{skill:"Assassination (AS):", description:"• When attacking an unaware humanoid from behind, an assassin gains a +4 bonus to hit. If the attack succeeds, the victim must save versus death with a penalty dependent on the assassin's level (noted in the table opposite). If the save fails, the victim is instantly killed, otherwise the assassin's attack inflicts normal damage."},
{skill:"Climb sheer surfaces (CS):", description:"• A roll is required for each 100' to be climbed. If the roll fails, the assassin falls at the half way point, suffering falling damage."},
{skill:"Hear noise (HN):", description:"• In a quiet environment (e.g. not in combat), an assassin may attempt to listen at a door or to hear the sounds of something (e.g. a wandering monster) approaching."},
{skill:"Hide in shadows (HS):", description:"• Requires the assassin to be motionless - attacking or moving while hiding is not possible."},
{skill:"Move silently (MS):", description:"• An assassin may attempt to sneak past enemies unnoticed."},
{skill:"Disguise:", description:"• Characters of any class may don disguises, but assassins are masters of the art - able to create disguises that pass even close scrutiny.", detection:"• Chance of detection: Everyone the assassin meets has a 2% chance of spotting the disguise. This roll is repeated once every subsequent day of meeting.", posing:"• Posing as another class, race, or sex: Increases the chance of being detected by 2% per change.", height:"• Height and weight: A disguise may alter height (up to 3 inches shorter or 5 inches taller) or weight (slightly thinner, much bulkier)."},
{skill:"Poison:", description:"• Victims of a poisoning by an assassin suffer a -2 penalty to the saving throw."}];

var barbarianSkills = [{skill:"Barbarian Skill Chance of Success:", level:1, cs:87, hd:10, ms:20},
{skill:"Climb sheer surfaces (CS):", description:"• Only applies to natural surfaces (e.g. tree trunks, cliff faces). A skill roll is required for each 100' height to be climbed. Failure indicates that the barbarian falls at the halfway point, suffering falling damage."},
{skill:"Hide in undergrowth (HD):", description:"• requires the barbarian must be motionless - attacking or moving while hiding is not possible."},
{skill:"Move silently (MS):", description:"• A barbarian may attempt to sneak past enemies."},
{skill:"Cure Poison:", description:"• In the wilderness, a barbarian can gather herbs to concoct an antidote to natural poisons. This takes one turn per character to be cured. Each subject may make a second save versus poison to end the effects."},
{skill:"Fear of Magic:", description:"• Barbarians are mistrustful of magic and will refuse to knowingly use or come under the influence of spells or magic items. Barbarians will accept divine magic associated with their tribal religion."},
{skill:"Foraging and hunting:", description:"• A party with a barbarian can more easily find food when foraging (2-in-6) or prey when hunting (5-in-6)."}];

var bardSkills = [{skill:"Anti-Charm:", description:"• While the bard plays music and sings, allies within 30' are immune to song-based magical effects and the beguiling powers of sylvan creatures or fairies. Allies already under the effect of such magic may make another saving throw with a +4 bonus."},
{skill:"Enchantment:", description:"• By playing music and singing, the bard can fascinate subjects in a 30' radius. This ability does not function in combat.", numberOfSubjects:"• Number of subjects: Up to 2HD of creatures per level of the bard are affected. The bard may choose to target a specific individual or a group (in which case, the affected individuals are determined randomly).", typeOfSubjects:"• Type of subjects: At 1st level, the bard can fascinate persons.", effect:"• Effect: Each subject must save versus spells or be fascinated, as follows:", rapt:"• Rapt: Fascinated subjects' attention is fully bent on the bard's performance, as long as it continues.", follow:"• Follow: The bard may walk while playing. Fascinated subjects will follow.", interruptions:"• Interruptions: If the performance is interrupted (e.g. by loud noise or violence), the fascination ends immediately."},
{skill:"Charming Fascinated Subjects:", description:"• If the bard performs for at least one turn and the performance ends without interruption, fascinated subjects may be placed under a deeper charm. Each subject must make another save versus spells (with a +2 bonus) or be charmed for one turn per level of the bard:", friendship:"• Friendship: Charmed subjects regard the bard as a trusted friend and ally and will come to the bard's defence.", commands:"• Commands: If they share a language, charmed subjects will obey the bard's commands.", alignment:"• Alingment: Commands that contradict the charmed creature's nature or alignment may be ignored.", suicidal: "• Suicidal commands: Charmed subjects never obey suicidal or obviously harmful orders."}];

var druidSkills = [{skill:"Spells:", spells:"• level 1 spells per day:", castableSpells:1},
{skill:"Divine Magic:", holySymbol:"• Holy symbol: A druid must carry a holy symbol: a sprig of mistletoe which the character must harvest.", disfavor:"• Deity disfavor: Druids must be faithful to the tenets of their alignment and religion. Druids who fall from favour with their deity may incur penalties.", research:"• Magical research: A druid of any level may spend time and money on magical research. This allows them to create new spells or other magical effects associated with their deity. When a druid reaches 9th level, they are also able to create magic items.", casting:"• Spell casting: A druid may pray to receive spells from nature. The power and number of spells available to a druid are determined by the character's perience level.", magicItems:"• Using magic items: As spell casters, druids can use magic scrolls of spells on their spell list. They can also use items that may only be used by divine spell casters (e.g. some staves). Druids may not use magical books or tomes."},
{skill:"Energy Resistance:", description:"• Druids gain +2 bonus to saving throws against electricity (lightning) and fire."},
{skill:"Identification:", description:"• Druids can identify all plants and animals and can disern pure water."},
{skill:"Languages:", description:"• Druids speak a secret tongue known only to their sect. At each level above 2nd, a druid also learns to speak a language used by creatures of Sylvan forests (e.g. dryads, green dragons, pixies, treants)."},
{skill:"Path-Finding:", description:"• A party with a druid has only a 1-in-6 chance of getting lost in woodlans."}];